### ISSUE TITLE
Create modals Design

### ISSUE THREAD

**Issue by Winkler102** [Winkler102/group8-Great#6]
### Goals
* A modal that pop ups after selecting Genre 
* Space for Movie Title and Summary
* Space for restaurant

**Comment by JohnWDevine85** [comment]
Added Modal Box, able to be opened and closed with default styling included. Not responsive designed or styled to theme yet.

**Comment by JohnWDevine85** [comment]
These are still needed but should be handled during CSS implementation : 

- Space for Movie Title and Summary
- Space for restaurant
